name: z-haskell
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  z-haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - z-haskell

tests:
  z-haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - z-haskell
